# This file allows testing your addon using travis CI servers to use it you'll need to
# create an account in travis.org and enable your addon there. 
#
# By default it will test linux 64bit and osx against the master and stable OF branches. 
# Other platforms can be enabled by uncommenting the corresponding sections.
#
# If any extra install is needed to use the addon it can be included in the corresponding
# install script in:
#
# scripts/ci/$TARGET/install.sh
#


language: c++
compiler: gcc
sudo: true
matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="rpi"
    addons:
      apt:
        packages:
        - qemu
        - qemu-user-static
        - binfmt-support
        - parted
        - wget
        - dosfstools
        - zip
    script:
    - sudo bash scripts/ci/
    - zip opm.img.zip opm.img

# Linux 64bit, OF master
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="linux64" OF_BRANCH="master"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
          - gdb

# OSX, OF master
  - os: osx
    osx_image: xcode8
    compiler: clang
    env: TARGET="osx" OF_BRANCH="master"

# Linux ARM7, OF stable:  Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="linuxarmv7l" OF_BRANCH="stable"
#    cache:
#      directories:
#        - ~/rpi2_toolchain
#        - ~/firmware-master
#        - ~/archlinux

  # Exclude the default build that would otherwise be generated
  # see https://github.com/travis-ci/travis-ci/issues/1228
  exclude:
    - compiler: gcc

install:
  - |
    if [ "${TARGET}" == "rpi" ]; then
      pwd
      echo "Launch rpi specific install script here."
      sudo bash ./scripts/ci/rpi/install.sh
    else
      cd ~
      git clone --depth=1 --branch=$OF_BRANCH https://github.com/openframeworks/openFrameworks
      cd ~/openFrameworks/addons
      git clone --depth=1 https://github.com/jeffcrouse/ofxJSON.git
      cd ~/openFrameworks
      scripts/ci/addons/install.sh
    fi

script:
  - |
    if [ "${TARGET}" == "rpi" ]; then
      pwd
      sudo bash ./scripts/ci/rpi/mkimage.sh
    else
      cd ~/openFrameworks
      scripts/ci/addons/build.sh
    fi

git:
  depth: 10